### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by robinsonjohn** [kasperlegarth/instastory.js#21]
I am getting inconsistent results using this plugin. At times, it works fine, then at other times, I get the following error in the console: `Uncaught TypeError: e.graphql is undefined`.

I am using this plugin with the [Missio theme](https://themeforest.net/item/missio-photography-template-for-photographers/23183247).

Any suggestions?

**Comment by kasperlegarth** [comment]
Hi,
First I just want to clarify that i have no association with elemis and the themes they sell on ThemeForest. They have just chosen to implement this plugin into their themes :) 

When that said, I will do my best to help you with your problem. But to do so, I need a little more info. Do you have an URL where I can inspect the problem?

**Comment by robinsonjohn** [comment]
Thanks for the response. I know you don't support the theme itself, but I am interested in utilizing this plugin on other sites myself.

The URL of the site in question is: [https://robinbarnesphotography.com/](https://robinbarnesphotography.com/)

Just above the footer is where it's used. The theme has included your plugin in the following file:

[https://robinbarnesphotography.com/assets/js/plugins.js](https://robinbarnesphotography.com/assets/js/plugins.js)

**Comment by elemis** [comment]
We are having this issue on all the websites we use the plugin as well as the original demo: https://kasperlegarth.github.io/instastory.js/
It returns "Uncaught TypeError: e.graphql is undefined." error most of the time and fails to work. 

When we check with a mobile device with cellular network sometimes it works properly there. Maybe this can give an idea of the cause?

**Comment by kasperlegarth** [comment]
@bayfrontmedia and @elemis - I have no issue seeing the sites.
As discussed here: https://github.com/kasperlegarth/instastory.js/issues/6 - There are limitations on the URL.

This is a security setting from Instagram to prevent attacks on the endpoint. The reason why it can help to switch to cellular networks is the new connection gives the device a new IP address. 

I'm guessing that the error is happening due to the development process where you typically refresh a site multiple times in a short time. This behavior is not normal for a typical visitor and should not be an issue. The fact that the call is made by the client means that is the users' IP address and not the servers that get blocked. That's also why you guys have the problem and do not.

I hope this clarify why this is happening

**Comment by elemis** [comment]
@kasperlegarth thank you for the explanation.

**Comment by kasperlegarth** [comment]
No problem :)
